plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id "com.google.protobuf" version "0.10.0"
}

group = 'ru.leti'

version = '2.0.0'
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}
configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

sourceSets {
	main {
		proto {
			srcDir 'src/main/resources/proto'
		}
	}
}

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
}

dependencies {
	// gRPC
	implementation 'org.springframework.boot:spring-boot-starter-grpc-server'
	implementation 'org.springframework.boot:spring-boot-starter-grpc-client'


	// Database
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.postgresql:postgresql:42.7.12'

	// Internal
	implementation 'com.github.wisetask:wise-task-library:1.0.10'

	// Observability (tracing, metrics, logs)
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
	implementation 'io.micrometer:micrometer-registry-prometheus'
	implementation 'com.github.loki4j:loki-logback-appender:2.1.0'

	// Lombok
	compileOnly 'org.projectlombok:lombok:1.18.46'
	annotationProcessor 'org.projectlombok:lombok:1.18.46'

	// Mapping
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
}

protobuf {
	protoc {
		artifact = 'com.google.protobuf:protoc'
	}
	plugins {
		grpc {
			artifact = 'io.grpc:protoc-gen-grpc-java'
		}
	}
	generateProtoTasks {
		all()*.plugins {
			grpc {}
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
