syntax = "proto3";

package ru.leti.wise.task.graph;

import "graph.proto";
import "pagination.proto";
import "google/protobuf/empty.proto";

service GraphService {
  rpc getGraphById (GetGraphByIdRequest) returns (GetGraphByIdResponse);
  rpc createGraph (CreateGraphRequest) returns (CreateGraphResponse);
  rpc generateRandomGraph (GenerateGraphRequest) returns (GenerateGraphResponse);
  rpc getAllGraphs(GetAllGraphsRequest) returns (GetAllGraphsResponse);
  rpc removeGraph (RemoveGraphRequest) returns (RemoveGraphResponse);
  rpc GetGraphsByIds(GraphIds) returns (GetGraphsByIdsResponse);
}
message GraphFilter {
  string id = 1;
  string authorId = 2;
  int32 vertexCount = 3;
  int32 edgeCount = 4;
  bool isDirect = 5;
  bool isNamed = 6;
  string name = 7;
}

message GetAllGraphsRequest {
  ru.leti.wise.task.pagination.PaginationRequest pagination = 1;
  GraphFilter filter = 2;
}

message GetAllGraphsResponse {
  repeated Graph items = 1;
  ru.leti.wise.task.pagination.PaginationResponse pagination = 2;
}

message GenerateGraphRequest {
  int32 vertexCount = 1;
  int32 edgeCount = 2;
  bool isDirect = 3;
  bool isSaved = 4;
}

message RemoveGraphRequest {
  string id = 1;
}

message RemoveGraphResponse {
  string id = 1;
}

message GetGraphLibraryResponse {
  repeated Graph graphList = 1;
}

message GenerateGraphResponse {
  Graph graph = 1;
}

message CreateGraphResponse {
  Graph graph = 1;
}

message CreateGraphRequest {
  Graph graph = 1;
}

message GetGraphByIdResponse {
  Graph graph = 1;
}

message GetGraphByIdRequest {
  string id = 1;
}

message GraphIds {
  repeated string graph_ids = 1;
}

message GetGraphsByIdsResponse {
  repeated Graph graphs = 1;
}